import React from 'react';
import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({
    "en": {
        Pay: "Pay",
        Request: "Request",
        Hello: "Hello",
        Ecommerce: "Ecommerce",
        SlideT1: "Buy&Sell your stuff locally",
        SlideB1: "SNAP.POST.SELL",
        Work: "Work",
        SlideT2: "Connect with top freelancers for your business need.",
        SlideB2: "Logos, web design and more.",
        Vacation: "Vacation",
        Rentals: "Rentals",
        SlideT3: "Book unique homes for your next vacation.",
        SlideB3: "SHARE. RENT. EARNED",
        Stocks: "Stocks",
        and: " and",
        cryptos: "cryptos",
        SlideT4: "Buy, Sell, exchange stocks and cryptocurrencies.",
        Estimated: "Estimated",
        Balance: "Balance",
        Reward: "Reward",
        point: "point",
        Verification: "Verification",
        SettingLanguage: "Setting Language",
        Personal: "Personal",
        Notifications: "Notifications",
        Merchant: "Merchant",
        Setting: "Setting",
        Wallets: "Wallets",
        Cashout: "Cash out",
        Portfolio: "Portfolio",
        Loans: "Loans",
        Cashin: "Cash-In",
        Guest: "Rent",
        Buysellitemfast: "Buy&sell",
        Cryptocurrencies: "Crypto currencies",
        Copysocialtrading: "Copy&Social trading",
        InviteFriends: "Invite Friends",
        Signout: "Sign Out",
        Verified:"Verified",
        Pending:"Pending",
        Rejected:"Rejected",
        Submit:"Submit",
        Verificationpage:"Verification page",
        Addressproof:"Address proof",
        Nameproof:"Name proof",
        Paywithoutrequest:"Pay without request",
        cancel:"cancel",
        Toyourcontacts:"To your contacts",
        from:"from",
        Exchange:"Exchange",
        Social:"Social",
    },
    "cn": {
        Pay: "工资",
        Request: "请求",
        Hello: "你好!",
        Ecommerce: "电子商务",
        SlideT1: "在本地购买和出售您的东西",
        SlideB1: "快照。开机自检。卖。",
        Work: "工作",
        SlideT2: "与顶尖的自由职业者联系，满足您的业务需求。",
        SlideB2: "徽标，网页设计等。",
        Vacation: "假期",
        Rentals: "租金",
        SlideT3: "预订下一个假期的独特房屋。",
        SlideB3: "分享。 出租。 赚来的。",
        Stocks: "股票",
        and: "与",
        cryptos: "加密货币",
        SlideT4: "买卖，交换股票和加密货币。",
        Estimated: "估计的",
        Balance: "平衡",
        Reward: "奖励",
        point: "目标",
        Verification: "验证",
        SettingLanguage: "设定语言",
        Personal: "个人",
        Notifications: "通知",
        Merchant: "商人",
        Setting: "设置",
        Wallets: "皮夹",
        Cashout: "兑现",
        Portfolio: "作品集",
        Loans: "贷款额",
        Cashin: "现金",
        Guest: "客人",
        Buysellitemfast: "买和出售物品",
        Cryptocurrencies: "加密货币",
        Copysocialtrading: "复制与社交交易",
        InviteFriends: "邀请朋友",
        Signout: "登出",
        Verified:"已验证",
        Pending:"待定",
        Rejected:"拒绝",
        Submit:"提交",
        Verificationpage:"验证页面",
        Addressproof:"地址证明",
        Nameproof:"名称证明",
        Paywithoutrequest:"无需付款",
        cancel:"取消",
        Toyourcontacts:"给你的联系人",
        from:"从",
        Exchange:"交换",
        Social:"社交",
    },

    "ko": {
        Pay: "지불",
        Request: "의뢰",
        Hello: "안녕하세요!",
        Ecommerce: "전자 상거래",
        SlideT1: "물건을 현지에서 구매 및 판매",
        SlideB1: "스냅, 포스트, 판매",
        Work: "작업",
        SlideT2: "비즈니스 요구에 따라 최고의 프리랜서와 연락하십시오.",
        SlideB2: "로고, 웹 디자인 등",
        Vacation: "휴가",
        Rentals: "대여",
        SlideT3: "다음 휴가를 위해 독특한 주택을 예약하십시오.",
        SlideB3: "공유. 임대. 획득",
        Stocks: "주식",
        and: "과",
        cryptos: "암호",
        SlideT4: "주식과 암호 화폐를 사고 팔고 교환합니다.",
        Estimated: "추정된",
        Balance: "균형",
        Reward: "보상",
        point: "점수",
        Verification: "확인",
        SettingLanguage: "언어 설정",
        Personal: "개인적인",
        Notifications: "알림",
        Merchant: "상인",
        Setting: "설정",
        Wallets: "지갑",
        Cashout: "현금인출",
        Portfolio: "대출",
        Loans: "대출",
        Cashin: "현금대출",
        Guest: "손님",
        Buysellitemfast: "구매 및 판매",
        Cryptocurrencies: "암호화 통화",
        Copysocialtrading: "복사 및 사회적 거래",
        InviteFriends: "친구 초대",
        Signout: "로그 아웃",
        Verified:"확인 됨",
        Pending:"대기 중",
        Rejected:"거부",
        Submit:"제출",
        Verificationpage:"확인 페이지",
        Addressproof:"주소 증명",
        Nameproof:"이름 증명",
        Paywithoutrequest:"요청없이 지불",
        cancel:"취소",
        Toyourcontacts:"연락처를 향해",
        from:"부터",
        Exchange:"교환",
        Social:"소셜",
    },
    // "hi": {
    //     first: "क्या हाल है ?",
    //     second: "मैं ठीक हूँ ?",
    // },
    // "ma": {
    //     first: "तू कसा आहेस ?",
    //     second: "मी ठीक आहे ?",
    // },
    // "fr": {
    //     first: "comment allez vous",
    //     second: "je vais bien",
    // }
});
export default strings;